plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel
env:
  node: true
  jest: true

extends:
  - 'airbnb-base'
  - 'prettier'

parser: babel-eslint

rules:
  code: 80
  no-console: 0
